import { funnelThemeFonts } from "@/lib/funnel-theme-fonts";
import type { ThemeStateMap, ResolvedFunnelTheme } from "@/lib/funnel-theme.types";

const defaultFonts = funnelThemeFonts.default;

const baseTextStyles = {
  headline: {
    color: "#0f172a",
    fontFamily: defaultFonts.headline,
    fontWeight: 800,
    fontSize: "clamp(2.25rem, 5vw, 3.75rem)",
    lineHeight: "1.05",
    letterSpacing: "-0.04em",
    textTransform: "none",
  },
  body: {
    color: "#1e293b",
    fontFamily: defaultFonts.body,
    fontWeight: 400,
    fontSize: "1rem",
    lineHeight: "1.75",
    letterSpacing: "0",
    textTransform: "none",
  },
  subheadline: {
    color: "#334155",
    fontFamily: defaultFonts.subheadline,
    fontWeight: 500,
    fontSize: "1.125rem",
    lineHeight: "1.6",
    letterSpacing: "-0.01em",
    textTransform: "none",
  },
  eyebrow: {
    color: "#0f172a",
    fontFamily: defaultFonts.subheadline,
    fontWeight: 700,
    fontSize: "0.75rem",
    lineHeight: "1.1",
    letterSpacing: "0.24em",
    textTransform: "uppercase",
  },
  caption: {
    color: "#64748b",
    fontFamily: defaultFonts.body,
    fontWeight: 400,
    fontSize: "0.875rem",
    lineHeight: "1.5",
    letterSpacing: "0",
    textTransform: "none",
  },
  price: {
    color: "#dc2626",
    fontFamily: defaultFonts.headline,
    fontWeight: 900,
    fontSize: "clamp(2rem, 4vw, 3.5rem)",
    lineHeight: "1",
    letterSpacing: "-0.05em",
    textTransform: "none",
  },
} as const satisfies ResolvedFunnelTheme["primitives"]["text"];

const buildButtonTextStates = (
  color: string,
  fontFamily: string,
  fontWeight: string | number,
): ThemeStateMap<ResolvedFunnelTheme["primitives"]["button"]["primary"]["text"]["rest"]> => ({
  rest: {
    color,
    fontFamily,
    fontWeight,
    fontSize: "0.9375rem",
    lineHeight: "1",
    letterSpacing: "-0.01em",
    textTransform: "uppercase",
  },
  hover: {
    color,
    fontFamily,
    fontWeight,
    fontSize: "0.9375rem",
    lineHeight: "1",
    letterSpacing: "-0.01em",
    textTransform: "uppercase",
  },
  active: {
    color,
    fontFamily,
    fontWeight,
    fontSize: "0.9375rem",
    lineHeight: "1",
    letterSpacing: "-0.01em",
    textTransform: "uppercase",
  },
  focus: {
    color,
    fontFamily,
    fontWeight,
    fontSize: "0.9375rem",
    lineHeight: "1",
    letterSpacing: "-0.01em",
    textTransform: "uppercase",
  },
  disabled: {
    color,
    fontFamily,
    fontWeight,
    fontSize: "0.9375rem",
    lineHeight: "1",
    letterSpacing: "-0.01em",
    textTransform: "uppercase",
  },
});

export const funnelBaseTheme = {
  tokens: {
    base: {
      pageBackground: "#f3f6fb",
      canvas: "#ffffff",
      surface: "#ffffff",
      surfaceMuted: "#f8fafc",
      surfaceEmphasis: "#0f172a",
      borderSubtle: "#e2e8f0",
      borderStrong: "#cbd5e1",
      overlay: "rgba(15, 23, 42, 0.92)",
    },
    text: {
      strong: "#0f172a",
      body: "#1e293b",
      muted: "#475569",
      subtle: "#64748b",
      inverse: "#f8fafc",
      accent: "#dc2626",
    },
    brand: {
      trust: "#2563eb",
      accent: "#dc2626",
      highlight: "#fef08a",
      success: "#059669",
      warning: "#f59e0b",
      danger: "#dc2626",
    },
    action: {
      primary: "#0f172a",
      primaryHover: "#1e293b",
      primaryActive: "#020617",
      secondary: "#ffffff",
      secondaryHover: "#f8fafc",
      secondaryActive: "#e2e8f0",
      urgency: "#f97316",
      urgencyHover: "#fb923c",
      urgencyActive: "#ea580c",
    },
    effects: {
      shadowXs: "0 1px 2px rgba(15, 23, 42, 0.06)",
      shadowSm: "0 10px 30px rgba(15, 23, 42, 0.06)",
      shadowMd: "0 20px 60px rgba(15, 23, 42, 0.08)",
      shadowLg: "0 24px 70px rgba(15, 23, 42, 0.12)",
      shadowXl: "0 34px 110px rgba(15, 23, 42, 0.18)",
      shadowCta: "0 18px 44px rgba(249, 115, 22, 0.28)",
      focusRingColor: "rgba(249, 115, 22, 0.35)",
      focusRingOffsetColor: "#ffffff",
    },
    radius: {
      sm: "0.75rem",
      md: "1rem",
      lg: "1.5rem",
      xl: "2rem",
      pill: "9999px",
    },
    fonts: defaultFonts,
  },
  primitives: {
    button: {
      primary: {
        surface: {
          rest: {
            backgroundColor: "#0f172a",
            borderColor: "#0f172a",
            shadow: "0 20px 40px rgba(15, 23, 42, 0.18)",
            radius: "1rem",
          },
          hover: {
            backgroundColor: "#1e293b",
            borderColor: "#1e293b",
            shadow: "0 24px 50px rgba(15, 23, 42, 0.22)",
            radius: "1rem",
          },
          active: {
            backgroundColor: "#020617",
            borderColor: "#020617",
            shadow: "0 12px 30px rgba(15, 23, 42, 0.2)",
            radius: "1rem",
          },
          focus: {
            backgroundColor: "#0f172a",
            borderColor: "#0f172a",
            shadow: "0 0 0 4px rgba(249, 115, 22, 0.35)",
            radius: "1rem",
          },
          disabled: {
            backgroundColor: "#94a3b8",
            borderColor: "#94a3b8",
            shadow: "none",
            radius: "1rem",
          },
        },
        text: buildButtonTextStates("#ffffff", defaultFonts.button, 800),
        borderWidth: "1px",
        outlineColor: "rgba(249, 115, 22, 0.35)",
        outlineOffset: "2px",
        gap: "0.5rem",
        paddingX: "1.5rem",
        paddingY: "1rem",
        minHeight: "3.25rem",
        motion: {
          duration: "200ms",
          easing: "cubic-bezier(0.22, 1, 0.36, 1)",
          transform: "translateY(-1px) scale(1.01)",
        },
      },
      secondary: {
        surface: {
          rest: {
            backgroundColor: "#ffffff",
            borderColor: "#cbd5e1",
            shadow: "0 10px 30px rgba(15, 23, 42, 0.06)",
            radius: "9999px",
          },
          hover: {
            backgroundColor: "#f8fafc",
            borderColor: "#94a3b8",
            shadow: "0 12px 36px rgba(15, 23, 42, 0.08)",
            radius: "9999px",
          },
          active: {
            backgroundColor: "#e2e8f0",
            borderColor: "#94a3b8",
            shadow: "0 6px 20px rgba(15, 23, 42, 0.08)",
            radius: "9999px",
          },
          focus: {
            backgroundColor: "#ffffff",
            borderColor: "#cbd5e1",
            shadow: "0 0 0 4px rgba(148, 163, 184, 0.28)",
            radius: "9999px",
          },
          disabled: {
            backgroundColor: "#f1f5f9",
            borderColor: "#e2e8f0",
            shadow: "none",
            radius: "9999px",
          },
        },
        text: buildButtonTextStates("#0f172a", defaultFonts.button, 600),
        borderWidth: "1px",
        outlineColor: "rgba(148, 163, 184, 0.28)",
        outlineOffset: "2px",
        gap: "0.5rem",
        paddingX: "1.25rem",
        paddingY: "0.875rem",
        minHeight: "3rem",
        motion: {
          duration: "180ms",
          easing: "cubic-bezier(0.22, 1, 0.36, 1)",
          transform: "translateY(-1px)",
        },
      },
      urgency: {
        surface: {
          rest: {
            backgroundColor: "#f97316",
            borderColor: "#f97316",
            shadow: "0 18px 44px rgba(249, 115, 22, 0.28)",
            radius: "1rem",
          },
          hover: {
            backgroundColor: "#fb923c",
            borderColor: "#fb923c",
            shadow: "0 22px 54px rgba(249, 115, 22, 0.32)",
            radius: "1rem",
          },
          active: {
            backgroundColor: "#ea580c",
            borderColor: "#ea580c",
            shadow: "0 12px 30px rgba(234, 88, 12, 0.26)",
            radius: "1rem",
          },
          focus: {
            backgroundColor: "#f97316",
            borderColor: "#f97316",
            shadow: "0 0 0 4px rgba(249, 115, 22, 0.35)",
            radius: "1rem",
          },
          disabled: {
            backgroundColor: "#fdba74",
            borderColor: "#fdba74",
            shadow: "none",
            radius: "1rem",
          },
        },
        text: buildButtonTextStates("#ffffff", defaultFonts.button, 900),
        borderWidth: "1px",
        outlineColor: "rgba(249, 115, 22, 0.35)",
        outlineOffset: "2px",
        gap: "0.5rem",
        paddingX: "1.5rem",
        paddingY: "1rem",
        minHeight: "3.25rem",
        motion: {
          duration: "200ms",
          easing: "cubic-bezier(0.22, 1, 0.36, 1)",
          transform: "translateY(-1px) scale(1.01)",
        },
      },
      handoff: {
        surface: {
          rest: {
            backgroundColor: "#059669",
            borderColor: "#059669",
            shadow: "0 18px 44px rgba(5, 150, 105, 0.24)",
            radius: "1rem",
          },
          hover: {
            backgroundColor: "#10b981",
            borderColor: "#10b981",
            shadow: "0 22px 54px rgba(5, 150, 105, 0.28)",
            radius: "1rem",
          },
          active: {
            backgroundColor: "#047857",
            borderColor: "#047857",
            shadow: "0 12px 30px rgba(4, 120, 87, 0.24)",
            radius: "1rem",
          },
          focus: {
            backgroundColor: "#059669",
            borderColor: "#059669",
            shadow: "0 0 0 4px rgba(5, 150, 105, 0.3)",
            radius: "1rem",
          },
          disabled: {
            backgroundColor: "#6ee7b7",
            borderColor: "#6ee7b7",
            shadow: "none",
            radius: "1rem",
          },
        },
        text: buildButtonTextStates("#ffffff", defaultFonts.button, 800),
        borderWidth: "1px",
        outlineColor: "rgba(5, 150, 105, 0.3)",
        outlineOffset: "2px",
        gap: "0.5rem",
        paddingX: "1.5rem",
        paddingY: "1rem",
        minHeight: "3.25rem",
        motion: {
          duration: "200ms",
          easing: "cubic-bezier(0.22, 1, 0.36, 1)",
          transform: "translateY(-1px)",
        },
      },
    },
    eyebrow: {
      pill: {
        surface: {
          backgroundColor: "#f1f5f9",
          borderColor: "#e2e8f0",
          shadow: "none",
          radius: "9999px",
        },
        text: {
          color: "#0f172a",
          fontFamily: defaultFonts.subheadline,
          fontWeight: 700,
          fontSize: "0.6875rem",
          lineHeight: "1",
          letterSpacing: "0.24em",
          textTransform: "uppercase",
        },
        paddingX: "1rem",
        paddingY: "0.5rem",
        alignment: "left",
      },
      attached: {
        surface: {
          backgroundColor: "#e6f7ff",
          borderColor: "#bfdbfe",
          shadow: "none",
          radius: "0 0 1rem 1rem",
        },
        text: {
          color: "#0f172a",
          fontFamily: defaultFonts.subheadline,
          fontWeight: 700,
          fontSize: "0.6875rem",
          lineHeight: "1",
          letterSpacing: "0.24em",
          textTransform: "uppercase",
        },
        paddingX: "1rem",
        paddingY: "0.5rem",
        alignment: "left",
      },
    },
    surface: {
      canvas: {
        surface: {
          backgroundColor: "#ffffff",
          borderColor: "#e2e8f0",
          shadow: "none",
          radius: "0",
        },
      },
      section: {
        surface: {
          backgroundColor: "#ffffff",
          borderColor: "#e2e8f0",
          shadow: "0 20px 60px rgba(15, 23, 42, 0.08)",
          radius: "2rem",
        },
      },
      sectionMuted: {
        surface: {
          backgroundColor: "#f8fafc",
          borderColor: "#e2e8f0",
          shadow: "0 20px 60px rgba(15, 23, 42, 0.06)",
          radius: "2rem",
        },
      },
      sectionEmphasis: {
        surface: {
          backgroundColor: "#0f172a",
          borderColor: "#1e293b",
          shadow: "0 34px 110px rgba(15, 23, 42, 0.22)",
          radius: "2rem",
        },
      },
      guaranteeCoupon: {
        surface: {
          backgroundColor: "#ffffff",
          borderColor: "#2563eb",
          shadow: "0 20px 60px rgba(15, 23, 42, 0.06)",
          radius: "2rem",
        },
      },
      overlay: {
        surface: {
          backgroundColor: "rgba(15, 23, 42, 0.92)",
          borderColor: "rgba(148, 163, 184, 0.22)",
          shadow: "0 -10px 20px rgba(0, 0, 0, 0.2)",
          radius: "0",
        },
      },
      urgencySection: {
        surface: {
          backgroundColor: "#fffaf5",
          borderColor: "#fed7aa",
          shadow: "0 20px 60px rgba(249, 115, 22, 0.08)",
          radius: "2rem",
        },
      },
    },
    text: baseTextStyles,
  },
  sections: {
    heroHook: {
      surface: "canvas",
      eyebrow: "attached",
      headline: "headline",
      body: "body",
      supportingText: "subheadline",
      primaryCta: "primary",
      secondaryCta: "secondary",
    },
    guarantee: {
      surface: "sectionMuted",
      eyebrow: "pill",
      headline: "headline",
      body: "body",
      supportingText: "caption",
      primaryCta: "urgency",
      secondaryCta: "secondary",
    },
    guaranteeSection: {
      surface: "guaranteeCoupon",
      eyebrow: "pill",
      headline: "headline",
      body: "body",
      supportingText: "caption",
      primaryCta: "primary",
      secondaryCta: "secondary",
    },
    finalCta: {
      surface: "sectionEmphasis",
      eyebrow: "pill",
      headline: "headline",
      body: "body",
      supportingText: "subheadline",
      primaryCta: "urgency",
      secondaryCta: "secondary",
    },
    urgencySection: {
      surface: "urgencySection",
      eyebrow: "pill",
      headline: "headline",
      body: "body",
      supportingText: "subheadline",
      primaryCta: "urgency",
      secondaryCta: "secondary",
    },
    offerStack: {
      surface: "section",
      eyebrow: "pill",
      headline: "headline",
      body: "body",
      supportingText: "caption",
      primaryCta: "urgency",
      secondaryCta: "secondary",
    },
    handoff: {
      surface: "sectionMuted",
      eyebrow: "pill",
      headline: "headline",
      body: "body",
      supportingText: "caption",
      primaryCta: "handoff",
      secondaryCta: "secondary",
    },
    stickyConversionBar: {
      surface: "overlay",
      text: "body",
      primaryCta: "urgency",
    },
    announcementBar: {
      surface: "sectionEmphasis",
      text: "eyebrow",
      emphasisColor: "#059669",
    },
    captureForm: {
      surface: "section",
      headline: "headline",
      body: "body",
      primaryCta: "primary",
    },
  },
} as const satisfies Omit<ResolvedFunnelTheme, "id" | "name" | "description">;
