export type MarketplaceStatus = "draft" | "active" | "archived" | string;

export type FunnelMarketplaceAsset = {
  templateKey: string;
  assetSlug?: string | null;
  blueprintKey: string;
  vertical?: string | null;
  industry?: string | null;
  subindustry?: string | null;
  businessModel?: string | null;
  funnelType?: string | null;
  funnelFormat?: string | null;
  framework?: string | null;
  objective?: string | null;
  stepsCount?: number | null;
  language?: string | null;
  country?: string | null;
  market?: string | null;
  level?: string | null;
  estimatedTimeMinutes?: number | null;
  tags?: string[];
  coverUrl?: string | null;
  thumbnailUrl?: string | null;
  screenshots?: unknown;
  videoPreviewUrl?: string | null;
  label: string;
  description: string;
  headline?: string | null;
  goal: string;
  recommendedFor: string;
  cta: string;
  pathSuggestion: string;
  difficulty: string;
  status?: MarketplaceStatus;
  version?: string;
  authorName?: string | null;
  publishedAt?: string | null;
  problemSolved?: string | null;
  idealFor?: string | null;
  flowSummary?: unknown;
  compatibleBlueprints?: string[];
  assets?: unknown;
  media?: unknown;
  history?: unknown;
  cloneCount?: number;
  activeInstallations?: number;
  lastActivatedAt?: string | null;
  favoriteCount?: number;
  hasMasterFunnel?: boolean;
  enabled?: boolean;
  source?: "master_clone" | "fallback";
  warning?: string;
  publicUrl?: string;
  sourceFunnelId?: string | null;
  sourceFunnelInstanceId?: string | null;
  builderUrl?: string | null;
};

export type MarketplaceMode = "admin" | "member";
