import type {
  AssignmentRecord,
  DomainRecord,
  EventRecord,
  FunnelInstanceRecord,
  FunnelPublicationRecord,
  FunnelTemplateRecord,
  LeadRecord,
  MemberProfile,
  RotationPoolRecord,
  SponsorRecord,
  TeamMetadata,
  WorkspaceRecord,
} from "@/lib/app-shell/types";

const now = "2026-03-21T15:10:00.000Z";

export const mockWorkspace: WorkspaceRecord = {
  id: "workspace-leadflow-dev",
  name: "Leadflow Dev Workspace",
  slug: "leadflow-dev",
  status: "active",
  timezone: "UTC",
  defaultCurrency: "USD",
  primaryLocale: "es",
  primaryDomain: "localhost",
  createdAt: now,
  updatedAt: now,
};

export const mockTeamMetadata: TeamMetadata[] = [
  {
    id: "team-sales-core",
    workspaceId: mockWorkspace.id,
    name: "Sales Core",
    code: "sales-core",
    status: "active",
    description: "Equipo operativo base para funnels, tracking y handoff.",
  },
];

export const mockTemplates: FunnelTemplateRecord[] = [
  {
    id: "template-simple-capture",
    workspaceId: null,
    name: "Leadflow Simple Capture v1",
    code: "lf-simple-capture-v1",
    status: "active",
    version: 1,
    funnelType: "simple_capture",
    blocksJson: {},
    mediaMap: {},
    settingsJson: {},
    allowedOverridesJson: {},
    defaultHandoffStrategyId: "handoff-deferred-queue",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "template-qualification-vsl",
    workspaceId: null,
    name: "Qualification VSL v1",
    code: "lf-vsl-qualification-v1",
    status: "draft",
    version: 1,
    funnelType: "vsl",
    blocksJson: {},
    mediaMap: {},
    settingsJson: {},
    allowedOverridesJson: {},
    defaultHandoffStrategyId: "handoff-deferred-queue",
    createdAt: now,
    updatedAt: now,
  },
];

export const mockFunnelInstances: FunnelInstanceRecord[] = [
  {
    id: "instance-core-acquisition",
    workspaceId: mockWorkspace.id,
    teamId: mockTeamMetadata[0].id,
    templateId: mockTemplates[0].id,
    legacyFunnelId: "legacy-core-acquisition",
    name: "Core Acquisition",
    code: "core-acquisition",
    status: "active",
    rotationPoolId: "pool-primary-sales",
    trackingProfileId: "tracking-meta-core",
    handoffStrategyId: "handoff-deferred-queue",
    settingsJson: {},
    mediaMap: {},
    stepIds: ["step-entry", "step-thank-you"],
    publicationIds: ["publication-root", "publication-opportunity"],
    createdAt: now,
    updatedAt: now,
  },
];

export const mockDomains: DomainRecord[] = [
  {
    id: "domain-localhost",
    workspaceId: mockWorkspace.id,
    teamId: mockTeamMetadata[0].id,
    host: "localhost",
    requestedHostname: "localhost",
    normalizedHost: "localhost",
    status: "active",
    onboardingStatus: "active",
    domainType: "system_subdomain",
    isPrimary: true,
    canonicalHost: "localhost",
    redirectToPrimary: false,
    verificationStatus: "verified",
    sslStatus: "active",
    verificationMethod: "none",
    cloudflareCustomHostnameId: null,
    cloudflareStatusJson: null,
    cnameTarget: null,
    fallbackOrigin: null,
    cloudflareHostnameStatus: null,
    cloudflareSslStatus: "active",
    cloudflareErrorMessage: null,
    dnsTarget: null,
    lastCloudflareSyncAt: null,
    activatedAt: now,
    dnsInstructions: [
      {
        id: "system-domain-managed",
        type: "info",
        host: "localhost",
        value:
          "Leadflow administra este subdominio desde su propio dominio base.",
        status: "managed",
        label: "Managed by Leadflow",
        detail: "No requiere que el team configure DNS manual.",
      },
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "domain-promo-acme",
    workspaceId: mockWorkspace.id,
    teamId: mockTeamMetadata[0].id,
    host: "promo.acme.test",
    requestedHostname: "promo.acme.test",
    normalizedHost: "promo.acme.test",
    status: "active",
    onboardingStatus: "active",
    domainType: "custom_subdomain",
    isPrimary: false,
    canonicalHost: "promo.acme.test",
    redirectToPrimary: false,
    verificationStatus: "verified",
    sslStatus: "active",
    verificationMethod: "cname",
    cloudflareCustomHostnameId: "cf-custom-hostname-promo-acme-test",
    cloudflareStatusJson: {
      id: "cf-custom-hostname-promo-acme-test",
      hostname: "promo.acme.test",
      status: "active",
      customOriginServer: "proxy-fallback.leadflow.kurukin.com",
      verificationErrors: [],
      ownershipVerification: null,
      ssl: {
        status: "active",
        method: "http",
        type: "dv",
        validationErrors: [],
        validationRecords: [],
      },
      error: null,
      raw: null,
    },
    cnameTarget: "customers.leadflow.kurukin.com",
    fallbackOrigin: "proxy-fallback.leadflow.kurukin.com",
    cloudflareHostnameStatus: "active",
    cloudflareSslStatus: "active",
    cloudflareErrorMessage: null,
    dnsTarget: "customers.leadflow.kurukin.com",
    lastCloudflareSyncAt: now,
    activatedAt: now,
    dnsInstructions: [
      {
        id: "cname-promo-acme-test",
        type: "cname",
        host: "promo.acme.test",
        value: "customers.leadflow.kurukin.com",
        status: "required",
        label: "CNAME required",
        detail:
          "Apunta el subdominio del cliente al target publico del SaaS. Cloudflare reenviara ese trafico al origin fijo proxy-fallback.leadflow.kurukin.com.",
      },
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "domain-cliente-demo",
    workspaceId: mockWorkspace.id,
    teamId: mockTeamMetadata[0].id,
    host: "cliente-demo.acme.test",
    requestedHostname: "cliente-demo.acme.test",
    normalizedHost: "cliente-demo.acme.test",
    status: "draft",
    onboardingStatus: "pending_dns",
    domainType: "custom_subdomain",
    isPrimary: false,
    canonicalHost: "cliente-demo.acme.test",
    redirectToPrimary: false,
    verificationStatus: "pending",
    sslStatus: "pending",
    verificationMethod: "cname",
    cloudflareCustomHostnameId: null,
    cloudflareStatusJson: null,
    cnameTarget: "customers.leadflow.kurukin.com",
    fallbackOrigin: "proxy-fallback.leadflow.kurukin.com",
    cloudflareHostnameStatus: null,
    cloudflareSslStatus: null,
    cloudflareErrorMessage: null,
    dnsTarget: "customers.leadflow.kurukin.com",
    lastCloudflareSyncAt: null,
    activatedAt: null,
    dnsInstructions: [
      {
        id: "cname-cliente-demo-acme-test",
        type: "cname",
        host: "cliente-demo.acme.test",
        value: "customers.leadflow.kurukin.com",
        status: "required",
        label: "CNAME required",
        detail:
          "Apunta el subdominio del cliente al target publico del SaaS. Cloudflare reenviara ese trafico al origin fijo proxy-fallback.leadflow.kurukin.com.",
      },
    ],
    createdAt: now,
    updatedAt: now,
  },
];

export const mockPublications: FunnelPublicationRecord[] = [
  {
    id: "publication-root",
    workspaceId: mockWorkspace.id,
    teamId: mockTeamMetadata[0].id,
    domainId: mockDomains[0].id,
    funnelInstanceId: mockFunnelInstances[0].id,
    trackingProfileId: "tracking-meta-core",
    handoffStrategyId: "handoff-deferred-queue",
    pathPrefix: "/",
    status: "active",
    isPrimary: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "publication-opportunity",
    workspaceId: mockWorkspace.id,
    teamId: mockTeamMetadata[0].id,
    domainId: mockDomains[0].id,
    funnelInstanceId: mockFunnelInstances[0].id,
    trackingProfileId: "tracking-meta-core",
    handoffStrategyId: "handoff-deferred-queue",
    pathPrefix: "/oportunidad",
    status: "active",
    isPrimary: false,
    createdAt: now,
    updatedAt: now,
  },
];

export const mockSponsors: SponsorRecord[] = [
  {
    id: "3be5f7f2-c6ae-47cb-a2bb-e1c869f7db11",
    workspaceId: mockWorkspace.id,
    teamId: mockTeamMetadata[0].id,
    displayName: "Ana Sponsor",
    status: "active",
    email: "ana@leadflow.local",
    phone: "+57 300 555 0101",
    availabilityStatus: "available",
    routingWeight: 1,
    memberPortalEnabled: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "88623ff4-fb9c-4040-b737-fca5ae259c79",
    workspaceId: mockWorkspace.id,
    teamId: mockTeamMetadata[0].id,
    displayName: "Bruno Sponsor",
    status: "active",
    email: "bruno@leadflow.local",
    phone: "+57 300 555 0102",
    availabilityStatus: "available",
    routingWeight: 1,
    memberPortalEnabled: true,
    createdAt: now,
    updatedAt: now,
  },
];

export const mockRotationPools: RotationPoolRecord[] = [
  {
    id: "pool-primary-sales",
    workspaceId: mockWorkspace.id,
    teamId: mockTeamMetadata[0].id,
    name: "Primary Sales Pool",
    status: "active",
    strategy: "round-robin",
    sponsorIds: mockSponsors.map((item) => item.id),
    funnelIds: ["legacy-core-acquisition"],
    isFallbackPool: false,
    createdAt: now,
    updatedAt: now,
  },
];

export const mockLeads: LeadRecord[] = [
  {
    id: "lead-maria-santos",
    workspaceId: mockWorkspace.id,
    funnelId: "legacy-core-acquisition",
    funnelInstanceId: mockFunnelInstances[0].id,
    funnelPublicationId: mockPublications[0].id,
    visitorId: "visitor-maria-santos",
    sourceChannel: "form",
    fullName: "Maria Santos",
    email: "maria@empresa.co",
    phone: "+57 310 222 3000",
    companyName: "Santos Growth",
    status: "assigned",
    qualificationGrade: "warm",
    summaryText: "Lead con intención clara y pendiente de contacto inicial.",
    nextActionLabel: "Enviar primer WhatsApp",
    followUpAt: "2026-03-22T16:00:00.000Z",
    lastContactedAt: "2026-03-21T12:05:00.000Z",
    lastQualifiedAt: "2026-03-21T12:04:00.000Z",
    currentAssignmentId: "assignment-maria-ana",
    reminderBucket: "overdue",
    reminderLabel: "Vencido",
    suggestedNextAction:
      "Resolver follow-up vencido. Enviar seguimiento con contexto y confirmar el siguiente paso.",
    effectiveNextAction: "Enviar primer WhatsApp",
    playbookKey: "active_nurture",
    playbookTitle: "Nurturing activo",
    playbookDescription:
      "El lead ya entro en conversacion y necesita seguimiento constante sin sobreoperarlo.",
    needsAttention: true,
    tags: ["runtime-v1", "qualified"],
    createdAt: "2026-03-21T12:00:00.000Z",
    updatedAt: "2026-03-21T12:02:00.000Z",
  },
  {
    id: "lead-carlos-rivera",
    workspaceId: mockWorkspace.id,
    funnelId: "legacy-core-acquisition",
    funnelInstanceId: mockFunnelInstances[0].id,
    funnelPublicationId: mockPublications[1].id,
    visitorId: "visitor-carlos-rivera",
    sourceChannel: "form",
    fullName: "Carlos Rivera",
    email: "carlos@rivera.io",
    phone: "+57 300 443 9010",
    companyName: "Rivera Studio",
    status: "qualified",
    qualificationGrade: "hot",
    summaryText: "Lead con alta intención y propuesta pendiente de envío.",
    nextActionLabel: "Enviar propuesta corta y confirmar demo",
    followUpAt: "2026-03-25T17:00:00.000Z",
    lastContactedAt: "2026-03-25T09:45:00.000Z",
    lastQualifiedAt: "2026-03-25T09:50:00.000Z",
    currentAssignmentId: "assignment-carlos-bruno",
    reminderBucket: "due_today",
    reminderLabel: "Hoy",
    suggestedNextAction:
      "Resolver seguimiento de hoy. Llevar el lead a llamada o propuesta con seguimiento corto.",
    effectiveNextAction: "Enviar propuesta corta y confirmar demo",
    playbookKey: "high_intent_close",
    playbookTitle: "Alta intención",
    playbookDescription:
      "Lead con señales de cierre. La operación debe avanzar hacia llamada, propuesta o siguiente decisión comercial.",
    needsAttention: true,
    tags: ["runtime-v1", "high-intent"],
    createdAt: "2026-03-21T12:10:00.000Z",
    updatedAt: "2026-03-21T12:12:00.000Z",
  },
  {
    id: "lead-andrea-lopez",
    workspaceId: mockWorkspace.id,
    funnelId: "legacy-core-acquisition",
    funnelInstanceId: mockFunnelInstances[0].id,
    funnelPublicationId: mockPublications[0].id,
    visitorId: "visitor-andrea-lopez",
    sourceChannel: "landing-page",
    fullName: "Andrea Lopez",
    email: "andrea@north.dev",
    phone: null,
    companyName: "North Dev",
    status: "captured",
    qualificationGrade: "cold",
    summaryText: "Aún no responde, mantener nurturing liviano.",
    nextActionLabel: "Revisar origen y reintentar mañana",
    followUpAt: "2026-03-23T14:00:00.000Z",
    lastContactedAt: null,
    lastQualifiedAt: null,
    currentAssignmentId: null,
    reminderBucket: "upcoming",
    reminderLabel: "Proximo",
    suggestedNextAction: "Reactivar con mensaje corto y validar timing real.",
    effectiveNextAction: "Revisar origen y reintentar mañana",
    playbookKey: "cold_reengage",
    playbookTitle: "Reactivacion fria",
    playbookDescription:
      "El lead necesita un reintento liviano y una validacion rapida de timing antes de seguir invirtiendo esfuerzo.",
    needsAttention: false,
    tags: ["nurture"],
    createdAt: "2026-03-21T13:00:00.000Z",
    updatedAt: "2026-03-21T13:03:00.000Z",
  },
  {
    id: "lead-lucia-mendez",
    workspaceId: mockWorkspace.id,
    funnelId: "legacy-core-acquisition",
    funnelInstanceId: mockFunnelInstances[0].id,
    funnelPublicationId: mockPublications[0].id,
    visitorId: "visitor-lucia-mendez",
    sourceChannel: "form",
    fullName: "Lucia Mendez",
    email: "lucia@mendez.mx",
    phone: "+52 55 9000 7788",
    companyName: "Mendez Retail",
    status: "assigned",
    qualificationGrade: null,
    summaryText: "Lead nuevo sin contacto ni seguimiento programado todavía.",
    nextActionLabel: null,
    followUpAt: null,
    lastContactedAt: null,
    lastQualifiedAt: null,
    currentAssignmentId: "assignment-lucia-bruno",
    reminderBucket: "unscheduled",
    reminderLabel: "Sin follow-up",
    suggestedNextAction:
      "Definir follow-up. Hacer primer contacto y dejar follow-up concreto para hoy.",
    effectiveNextAction:
      "Definir follow-up. Hacer primer contacto y dejar follow-up concreto para hoy.",
    playbookKey: "first_contact",
    playbookTitle: "Primer contacto",
    playbookDescription:
      "La prioridad es tomar ownership del lead rápido y abrir la primera conversación con contexto.",
    needsAttention: false,
    tags: ["new", "unscheduled"],
    createdAt: "2026-03-25T11:01:00.000Z",
    updatedAt: "2026-03-25T11:01:00.000Z",
  },
];

export const mockAssignments: AssignmentRecord[] = [
  {
    id: "assignment-maria-ana",
    workspaceId: mockWorkspace.id,
    leadId: mockLeads[0].id,
    sponsorId: mockSponsors[0].id,
    teamId: mockTeamMetadata[0].id,
    funnelId: "legacy-core-acquisition",
    funnelInstanceId: mockFunnelInstances[0].id,
    funnelPublicationId: mockPublications[0].id,
    rotationPoolId: mockRotationPools[0].id,
    status: "assigned",
    reason: "rotation",
    assignedAt: "2026-03-21T12:02:00.000Z",
    resolvedAt: null,
    createdAt: "2026-03-21T12:02:00.000Z",
    updatedAt: "2026-03-21T12:02:00.000Z",
  },
  {
    id: "assignment-carlos-bruno",
    workspaceId: mockWorkspace.id,
    leadId: mockLeads[1].id,
    sponsorId: mockSponsors[1].id,
    teamId: mockTeamMetadata[0].id,
    funnelId: "legacy-core-acquisition",
    funnelInstanceId: mockFunnelInstances[0].id,
    funnelPublicationId: mockPublications[1].id,
    rotationPoolId: mockRotationPools[0].id,
    status: "accepted",
    reason: "rotation",
    assignedAt: "2026-03-21T12:12:00.000Z",
    resolvedAt: null,
    createdAt: "2026-03-21T12:12:00.000Z",
    updatedAt: "2026-03-21T12:18:00.000Z",
  },
  {
    id: "assignment-lucia-bruno",
    workspaceId: mockWorkspace.id,
    leadId: mockLeads[3].id,
    sponsorId: mockSponsors[1].id,
    teamId: mockTeamMetadata[0].id,
    funnelId: "legacy-core-acquisition",
    funnelInstanceId: mockFunnelInstances[0].id,
    funnelPublicationId: mockPublications[0].id,
    rotationPoolId: mockRotationPools[0].id,
    status: "assigned",
    reason: "rotation",
    assignedAt: "2026-03-25T11:01:00.000Z",
    resolvedAt: null,
    createdAt: "2026-03-25T11:01:00.000Z",
    updatedAt: "2026-03-25T11:01:00.000Z",
  },
];

export const mockEvents: EventRecord[] = [
  {
    id: "event-funnel-viewed",
    workspaceId: mockWorkspace.id,
    eventId: "event-funnel-viewed",
    aggregateType: "funnel-publication",
    aggregateId: mockPublications[0].id,
    eventName: "funnel_viewed",
    actorType: "visitor",
    payload: { source: "browser" },
    occurredAt: "2026-03-21T11:59:30.000Z",
    funnelInstanceId: mockFunnelInstances[0].id,
    funnelPublicationId: mockPublications[0].id,
    funnelStepId: null,
    visitorId: null,
    leadId: null,
    assignmentId: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "event-lead-created",
    workspaceId: mockWorkspace.id,
    eventId: "event-lead-created",
    aggregateType: "lead",
    aggregateId: mockLeads[0].id,
    eventName: "lead_created",
    actorType: "visitor",
    payload: { source: "server" },
    occurredAt: "2026-03-21T12:01:40.000Z",
    funnelInstanceId: mockFunnelInstances[0].id,
    funnelPublicationId: mockPublications[0].id,
    funnelStepId: "step-entry",
    visitorId: mockLeads[0].visitorId,
    leadId: mockLeads[0].id,
    assignmentId: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "event-assignment-created",
    workspaceId: mockWorkspace.id,
    eventId: "event-assignment-created",
    aggregateType: "assignment",
    aggregateId: mockAssignments[0].id,
    eventName: "assignment_created",
    actorType: "system",
    payload: { source: "server" },
    occurredAt: "2026-03-21T12:02:00.000Z",
    funnelInstanceId: mockFunnelInstances[0].id,
    funnelPublicationId: mockPublications[0].id,
    funnelStepId: "step-entry",
    visitorId: null,
    leadId: mockLeads[0].id,
    assignmentId: mockAssignments[0].id,
    createdAt: now,
    updatedAt: now,
  },
];

export const mockMemberProfile: MemberProfile = {
  title: "Closer inbound",
  focus: "Seguimiento de oportunidades con handoff diferido.",
  timezone: "UTC-5",
  responseWindow: "15 min promedio",
  channels: ["Email", "WhatsApp", "Llamada"],
  notes:
    "Perfil demo sin auth real. En fases posteriores se reemplaza por preferencias persistidas del sponsor autenticado.",
};
