import type {
  AssignmentRecord,
  DomainRecord,
  EventRecord,
  FunnelInstanceRecord,
  FunnelPublicationRecord,
  FunnelTemplateRecord,
  LeadRecord,
  MemberProfile,
  RotationPoolRecord,
  SponsorRecord,
  TeamMetadata,
  WorkspaceRecord,
} from "@/lib/app-shell/types";

const now = "2026-03-21T15:10:00.000Z";

export const mockWorkspace: WorkspaceRecord = {
  id: "workspace-leadflow-dev",
  name: "Leadflow Dev Workspace",
  slug: "leadflow-dev",
  status: "active",
  timezone: "UTC",
  defaultCurrency: "USD",
  primaryLocale: "es",
  primaryDomain: "localhost",
  createdAt: now,
  updatedAt: now,
};

export const mockTeamMetadata: TeamMetadata[] = [
  {
    id: "team-sales-core",
    workspaceId: mockWorkspace.id,
    name: "Sales Core",
    code: "sales-core",
    status: "active",
    description: "Equipo operativo base para funnels, tracking y handoff.",
  },
];

export const mockTemplates: FunnelTemplateRecord[] = [
  {
    id: "template-simple-capture",
    workspaceId: null,
    name: "Leadflow Simple Capture v1",
    code: "lf-simple-capture-v1",
    status: "active",
    version: 1,
    funnelType: "simple_capture",
    blocksJson: {},
    mediaMap: {},
    settingsJson: {},
    allowedOverridesJson: {},
    defaultHandoffStrategyId: "handoff-deferred-queue",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "template-qualification-vsl",
    workspaceId: null,
    name: "Qualification VSL v1",
    code: "lf-vsl-qualification-v1",
    status: "draft",
    version: 1,
    funnelType: "vsl",
    blocksJson: {},
    mediaMap: {},
    settingsJson: {},
    allowedOverridesJson: {},
    defaultHandoffStrategyId: "handoff-deferred-queue",
    createdAt: now,
    updatedAt: now,
  },
];

export const mockFunnelInstances: FunnelInstanceRecord[] = [
  {
    id: "instance-core-acquisition",
    workspaceId: mockWorkspace.id,
    teamId: mockTeamMetadata[0].id,
    templateId: mockTemplates[0].id,
    legacyFunnelId: "legacy-core-acquisition",
    name: "Core Acquisition",
    code: "core-acquisition",
    status: "active",
    rotationPoolId: "pool-primary-sales",
    trackingProfileId: "tracking-meta-core",
    handoffStrategyId: "handoff-deferred-queue",
    settingsJson: {},
    mediaMap: {},
    stepIds: ["step-entry", "step-thank-you"],
    publicationIds: ["publication-root", "publication-opportunity"],
    createdAt: now,
    updatedAt: now,
  },
];

export const mockDomains: DomainRecord[] = [
  {
    id: "domain-localhost",
    workspaceId: mockWorkspace.id,
    teamId: mockTeamMetadata[0].id,
    host: "localhost",
    status: "active",
    kind: "apex",
    isPrimary: true,
    createdAt: now,
    updatedAt: now,
  },
];

export const mockPublications: FunnelPublicationRecord[] = [
  {
    id: "publication-root",
    workspaceId: mockWorkspace.id,
    teamId: mockTeamMetadata[0].id,
    domainId: mockDomains[0].id,
    funnelInstanceId: mockFunnelInstances[0].id,
    trackingProfileId: "tracking-meta-core",
    handoffStrategyId: "handoff-deferred-queue",
    pathPrefix: "/",
    status: "active",
    isPrimary: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "publication-opportunity",
    workspaceId: mockWorkspace.id,
    teamId: mockTeamMetadata[0].id,
    domainId: mockDomains[0].id,
    funnelInstanceId: mockFunnelInstances[0].id,
    trackingProfileId: "tracking-meta-core",
    handoffStrategyId: "handoff-deferred-queue",
    pathPrefix: "/oportunidad",
    status: "active",
    isPrimary: false,
    createdAt: now,
    updatedAt: now,
  },
];

export const mockSponsors: SponsorRecord[] = [
  {
    id: "3be5f7f2-c6ae-47cb-a2bb-e1c869f7db11",
    workspaceId: mockWorkspace.id,
    teamId: mockTeamMetadata[0].id,
    displayName: "Ana Sponsor",
    status: "active",
    email: "ana@leadflow.local",
    phone: "+57 300 555 0101",
    availabilityStatus: "available",
    routingWeight: 1,
    memberPortalEnabled: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "88623ff4-fb9c-4040-b737-fca5ae259c79",
    workspaceId: mockWorkspace.id,
    teamId: mockTeamMetadata[0].id,
    displayName: "Bruno Sponsor",
    status: "active",
    email: "bruno@leadflow.local",
    phone: "+57 300 555 0102",
    availabilityStatus: "available",
    routingWeight: 1,
    memberPortalEnabled: true,
    createdAt: now,
    updatedAt: now,
  },
];

export const mockRotationPools: RotationPoolRecord[] = [
  {
    id: "pool-primary-sales",
    workspaceId: mockWorkspace.id,
    teamId: mockTeamMetadata[0].id,
    name: "Primary Sales Pool",
    status: "active",
    strategy: "round-robin",
    sponsorIds: mockSponsors.map((item) => item.id),
    funnelIds: ["legacy-core-acquisition"],
    isFallbackPool: false,
    createdAt: now,
    updatedAt: now,
  },
];

export const mockLeads: LeadRecord[] = [
  {
    id: "lead-maria-santos",
    workspaceId: mockWorkspace.id,
    funnelId: "legacy-core-acquisition",
    funnelInstanceId: mockFunnelInstances[0].id,
    funnelPublicationId: mockPublications[0].id,
    visitorId: "visitor-maria-santos",
    sourceChannel: "form",
    fullName: "Maria Santos",
    email: "maria@empresa.co",
    phone: "+57 310 222 3000",
    companyName: "Santos Growth",
    status: "assigned",
    currentAssignmentId: "assignment-maria-ana",
    tags: ["runtime-v1", "qualified"],
    createdAt: "2026-03-21T12:00:00.000Z",
    updatedAt: "2026-03-21T12:02:00.000Z",
  },
  {
    id: "lead-carlos-rivera",
    workspaceId: mockWorkspace.id,
    funnelId: "legacy-core-acquisition",
    funnelInstanceId: mockFunnelInstances[0].id,
    funnelPublicationId: mockPublications[1].id,
    visitorId: "visitor-carlos-rivera",
    sourceChannel: "form",
    fullName: "Carlos Rivera",
    email: "carlos@rivera.io",
    phone: "+57 300 443 9010",
    companyName: "Rivera Studio",
    status: "assigned",
    currentAssignmentId: "assignment-carlos-bruno",
    tags: ["runtime-v1"],
    createdAt: "2026-03-21T12:10:00.000Z",
    updatedAt: "2026-03-21T12:12:00.000Z",
  },
  {
    id: "lead-andrea-lopez",
    workspaceId: mockWorkspace.id,
    funnelId: "legacy-core-acquisition",
    funnelInstanceId: mockFunnelInstances[0].id,
    funnelPublicationId: mockPublications[0].id,
    visitorId: "visitor-andrea-lopez",
    sourceChannel: "landing-page",
    fullName: "Andrea Lopez",
    email: "andrea@north.dev",
    phone: null,
    companyName: "North Dev",
    status: "captured",
    currentAssignmentId: null,
    tags: ["nurture"],
    createdAt: "2026-03-21T13:00:00.000Z",
    updatedAt: "2026-03-21T13:03:00.000Z",
  },
];

export const mockAssignments: AssignmentRecord[] = [
  {
    id: "assignment-maria-ana",
    workspaceId: mockWorkspace.id,
    leadId: mockLeads[0].id,
    sponsorId: mockSponsors[0].id,
    teamId: mockTeamMetadata[0].id,
    funnelId: "legacy-core-acquisition",
    funnelInstanceId: mockFunnelInstances[0].id,
    funnelPublicationId: mockPublications[0].id,
    rotationPoolId: mockRotationPools[0].id,
    status: "assigned",
    reason: "rotation",
    assignedAt: "2026-03-21T12:02:00.000Z",
    resolvedAt: null,
    createdAt: "2026-03-21T12:02:00.000Z",
    updatedAt: "2026-03-21T12:02:00.000Z",
  },
  {
    id: "assignment-carlos-bruno",
    workspaceId: mockWorkspace.id,
    leadId: mockLeads[1].id,
    sponsorId: mockSponsors[1].id,
    teamId: mockTeamMetadata[0].id,
    funnelId: "legacy-core-acquisition",
    funnelInstanceId: mockFunnelInstances[0].id,
    funnelPublicationId: mockPublications[1].id,
    rotationPoolId: mockRotationPools[0].id,
    status: "accepted",
    reason: "rotation",
    assignedAt: "2026-03-21T12:12:00.000Z",
    resolvedAt: null,
    createdAt: "2026-03-21T12:12:00.000Z",
    updatedAt: "2026-03-21T12:18:00.000Z",
  },
];

export const mockEvents: EventRecord[] = [
  {
    id: "event-funnel-viewed",
    workspaceId: mockWorkspace.id,
    eventId: "event-funnel-viewed",
    aggregateType: "funnel-publication",
    aggregateId: mockPublications[0].id,
    eventName: "funnel_viewed",
    actorType: "visitor",
    payload: { source: "browser" },
    occurredAt: "2026-03-21T11:59:30.000Z",
    funnelInstanceId: mockFunnelInstances[0].id,
    funnelPublicationId: mockPublications[0].id,
    funnelStepId: null,
    visitorId: null,
    leadId: null,
    assignmentId: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "event-lead-created",
    workspaceId: mockWorkspace.id,
    eventId: "event-lead-created",
    aggregateType: "lead",
    aggregateId: mockLeads[0].id,
    eventName: "lead_created",
    actorType: "visitor",
    payload: { source: "server" },
    occurredAt: "2026-03-21T12:01:40.000Z",
    funnelInstanceId: mockFunnelInstances[0].id,
    funnelPublicationId: mockPublications[0].id,
    funnelStepId: "step-entry",
    visitorId: mockLeads[0].visitorId,
    leadId: mockLeads[0].id,
    assignmentId: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "event-assignment-created",
    workspaceId: mockWorkspace.id,
    eventId: "event-assignment-created",
    aggregateType: "assignment",
    aggregateId: mockAssignments[0].id,
    eventName: "assignment_created",
    actorType: "system",
    payload: { source: "server" },
    occurredAt: "2026-03-21T12:02:00.000Z",
    funnelInstanceId: mockFunnelInstances[0].id,
    funnelPublicationId: mockPublications[0].id,
    funnelStepId: "step-entry",
    visitorId: null,
    leadId: mockLeads[0].id,
    assignmentId: mockAssignments[0].id,
    createdAt: now,
    updatedAt: now,
  },
];

export const mockMemberProfile: MemberProfile = {
  title: "Closer inbound",
  focus: "Seguimiento de oportunidades con handoff diferido.",
  timezone: "UTC-5",
  responseWindow: "15 min promedio",
  channels: ["Email", "WhatsApp", "Llamada"],
  notes:
    "Perfil demo sin auth real. En fases posteriores se reemplaza por preferencias persistidas del sponsor autenticado.",
};
