export const WORKSPACE_REPOSITORY = Symbol('WORKSPACE_REPOSITORY');
export const TEAM_REPOSITORY = Symbol('TEAM_REPOSITORY');
export const SPONSOR_REPOSITORY = Symbol('SPONSOR_REPOSITORY');
export const FUNNEL_REPOSITORY = Symbol('FUNNEL_REPOSITORY');
export const DOMAIN_REPOSITORY = Symbol('DOMAIN_REPOSITORY');
export const FUNNEL_TEMPLATE_REPOSITORY = Symbol('FUNNEL_TEMPLATE_REPOSITORY');
export const FUNNEL_INSTANCE_REPOSITORY = Symbol('FUNNEL_INSTANCE_REPOSITORY');
export const FUNNEL_STEP_REPOSITORY = Symbol('FUNNEL_STEP_REPOSITORY');
export const FUNNEL_PUBLICATION_REPOSITORY = Symbol(
  'FUNNEL_PUBLICATION_REPOSITORY',
);
export const TRACKING_PROFILE_REPOSITORY = Symbol(
  'TRACKING_PROFILE_REPOSITORY',
);
export const HANDOFF_STRATEGY_REPOSITORY = Symbol(
  'HANDOFF_STRATEGY_REPOSITORY',
);
export const CONVERSION_EVENT_MAPPING_REPOSITORY = Symbol(
  'CONVERSION_EVENT_MAPPING_REPOSITORY',
);
export const ROTATION_POOL_REPOSITORY = Symbol('ROTATION_POOL_REPOSITORY');
export const VISITOR_REPOSITORY = Symbol('VISITOR_REPOSITORY');
export const LEAD_REPOSITORY = Symbol('LEAD_REPOSITORY');
export const ASSIGNMENT_REPOSITORY = Symbol('ASSIGNMENT_REPOSITORY');
export const DOMAIN_EVENT_REPOSITORY = Symbol('DOMAIN_EVENT_REPOSITORY');
